spring:
  application:
    name: s3sample

aws:
  s3:
    region: ap-northeast-3
    bucket-name: ${AWS_S3_BUCKET_NAME:my-bucket}
    access-key-id: ${AWS_ACCESS_KEY_ID:}
    secret-access-key: ${AWS_SECRET_ACCESS_KEY:}
